spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: MyNewPass5!
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

### Swagger open or not.
swagger:
  enable: true